### ISSUE TITLE
#1 Validate Password & Email format

### ISSUE THREAD

**Issue by JosteinRuen** [boolean-uk/team-dev-client-ex-2410-team1#14]
- The email address must be in a valid format (e.g. abc@abc)
- The password should not be less than 8 characters in length
- The password should contain at least one uppercase character
- The password should contain at least one number
- The password should contain at least one special character

File structure:
src/pages/register/index.js
src/pages/login/index.js
src/validation/validation.js

TODOS:
Implement logic based on the specifications above in a separate file
--> Implement an error message in form of a text popup to the user when something is wrong to guide the user

* Text pop up: This will be a conditional render based on the validation of the email/password

**Comment by dogezen** [comment]
OK - would be good to have left a note here to add the validations in a utils file since they are used by login and register. You only mention register above, but the login page (and the profile pages) are going to use the same validations.
