### ISSUE TITLE
PRIORITY: Extend the AuthContext / AuthProvider to store user details

### ISSUE THREAD

**Issue by johnfa1508** [boolean-uk/team-dev-client-ex-2410-team1#25]
Update the AuthProvider inside auth.js by making a state that stores user details which is then returned by AuthProvider.

* When a user logs in or a user registers, this state will be set using the API response.
* When a user logs out, set this state back to null

**Remember to update this user context every time the user gets updated. 
Example: when creating profile, when editing in the profile etc...**

File structure:
UPDATE: src/context/auth.js

**Comment by dogezen** [comment]
a) where are you going to store the current' users' data (local storage?; when?)
b) when is the user data being loaded?
c) what user properties are going to be stored in the UserContext?

**Comment by dogezen** [comment]
Title is unclear, better something like: "PRIORITY: store logged in user details in UserContext with UserProvider"

**Comment by allendewilzin** [comment]
Looks good 👍🏻
