### ISSUE TITLE
#6 & 7 Dashboard postfeed implementation

### ISSUE THREAD

**Issue by johnfa1508** [boolean-uk/team-dev-client-ex-2410-team1#28]
**Posts Feed**

When a user is logged in, they should be redirected to the dashboard which displays:

- a feed with posts made by all users, sorted by most recent post
- an input to create a new post
- a search bar
- a list of other users in the logged in users cohort

[Postfeed design](https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy%3A-Cohort-Manager-app---Designs?node-id=135-15021&t=qbURw5nO4Y6jZyZY-0)

Each post in the post feed should be displayed as its own UI card containing:

- The author’s first name and last name
- The date & time of the post
- A button with 3 dots the user can click (if it is their post), allowing them to delete or edit the post
- The author’s initials in a coloured circle
- The post content
- A like button with a heart icon
- A comment button with a speech bubble icon
- The number of likes that the post has, or a message that tells the user they will be the first to like the post
- A list of comments the post has
- A comment input with the logged in users initials displayed in a coloured circle to the left side

[Design](https://www.figma.com/design/j9QIHvgM0wOVw3xDe9KdWB/My-Copy%3A-Cohort-Manager-app---Designs?node-id=135-15021&t=qbURw5nO4Y6jZyZY-0)

File structure:
UPDATE src/components/createPostModal
UPDATE src/components/posts
UPDATE src/components/post
UPDATE src/components/comments

TODO:
* Update createPostModal-component onSubmit so that it runs a POST request to API /posts
|--> Render the new comment after submitting, achievable by running the useEffect when the posts/setposts state gets changed
* Sort by most recent post, 
|--> Example: posts.slice().reverse().map
* Implement post-styling based on figma design above

**Comment by allendewilzin** [comment]
👍🏻 Looks good love the layout. helps alot and easier to read
