### ISSUE TITLE
FIX: loggedinuser state inside auth.js is null when page is refreshed

### ISSUE THREAD

**Issue by johnfa1508** [boolean-uk/team-dev-client-ex-2410-team1#29]
Change the user state that stores a logged in user's information inside AuthProvider in auth.js. Currently the state turns to null when a page is refreshed.

TODO
* Store user information inside localStorage instead of just a state

**Comment by dogezen** [comment]
ok, approved, but make sure to use JSON.stringify to store the js object as a string and JSON.parse to read it back into a JS object when loading.

Also, make sure to test for a null localStorage value on loading, JSON.parse may fail if the value is not a string and is undefined/null.
