### ISSUE TITLE
Cohort Page - Student View

### ISSUE THREAD

**Issue by JosteinRuen** [boolean-uk/team-dev-client-ex-2410-team1#31]
Student users who click the "Cohort" link in the left navigation bar should be directed to a page that shows all of the students in their cohort, as well as a list of teachers.

When the user clicks on a student, it should direct them to that student's profile.

Additionally, the student should see high-level statistics about the exercises, units, and modules they have completed, displayed in an "Exercises" section as shown in the design. This section can be hard-coded if exercise functionality has not yet been implemented.

ToDos:

Implement routing to ensure the "Cohort" link directs users to this page.
Display a list of students in the cohort, showing their initials, full name, and an option menu for additional actions.
Display a list of teachers associated with the cohort, including initials, name, and specialization.
Make each student clickable, directing to their profile page upon click.
Add the "My Exercises" section showing modules, units, and exercises completed, which can be hard-coded if necessary.

**Comment by allendewilzin** [comment]
Looks good hope this gets done today.
